name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ubuntu-22.04-jdk-17-ndk-r26b.dockerfile # Specify the Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ubuntu-22.04-jdk-17-ndk-r26b:latest
            ${{ secrets.DOCKER_USERNAME }}/ubuntu-22.04-jdk-17-ndk-r26b:sdk-51

      # Optional: Test the built image
      - name: Test Docker Image
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/custom-ndk-nodejs:latest node --version
